impl_libs = # Implementation libs.
import impl_libs += imgui-platform-win32%lib{imgui-platform-win32}
import impl_libs += imgui-render-dx10%lib{imgui-render-dx10}

exe{example_glfw_dx10} : cxx{*} $impl_libs