impl_libs = # Implementation libs.
import impl_libs += libimgui-platform-glfw%lib{imgui-platform-glfw}
import impl_libs += libimgui-render-opengl3%lib{imgui-render-opengl3}

exe{example_glfw_opengl3} : cxx{*} $impl_libs
