intf_libs = # Interface dependencies.
import intf_libs += imgui%lib{imgui}
impl_libs = # Implementation dependencies.

lib{imgui-platform-win32}: {hxx cxx}{**} $impl_libs $intf_libs

# Build options.
out_pfx_inc = [dir_path] $out_root/imgui/
src_pfx_inc = [dir_path] $src_root/imgui/

cxx.poptions =+ "-I$out_pfx_inc" "-I$src_pfx_inc" -DIMGUI_EXPORT

{hbmia obja}{*}: cxx.poptions += -DIMGUI_PLATFORM_WIN32_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DIMGUI_PLATFORM_WIN32_SHARED_BUILD

# Export options.
lib{imgui-platform-win32}:
{
    cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
    cxx.export.libs = $intf_libs
}

liba{imgui-platform-win32}: cxx.export.poptions += -DIMGUI_PLATFORM_WIN32_STATIC
libs{imgui-platform-win32}: cxx.export.poptions += -DIMGUI_PLATFORM_WIN32_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
    lib{imgui-platform-win32}: bin.lib.version = "-$version.project_id"
else
    lib{imgui-platform-win32}: bin.lib.version = "-$version.major.$version.minor"

hxx{*}:
{
    install = include/
    install.subdirs = true
}
