intf_libs = # Interface dependencies.
import intf_libs += imgui%lib{imgui}

platform_libs = # Platform specific libraries.
if $cxx.target.system == 'mingw32'
	platform_libs = -ld3d12 -ld3dcompiler -ldxgi
else
	platform_libs = d3d12.lib d3dcompiler.lib dxgi.lib

lib{imgui-render-dx12}: {hxx cxx}{**} $intf_libs

cxx.libs += $platform_libs
cxx.poptions += "-I$out_base" "-I$src_base" -DIMGUI_EXPORT

# Export options.
lib{imgui-render-dx12}:
{
    cxx.export.poptions = "-I$out_base" "-I$src_base"
    cxx.export.libs = $intf_libs $platform_libs
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
    lib{imgui-render-dx12}: bin.lib.version = "-$version.project_id"
else
    lib{imgui-render-dx12}: bin.lib.version = "-$version.major.$version.minor"

hxx{*}:
{
    install = include/imgui/backends/
}
