intf_libs = # Interface dependencies.
import intf_libs += imgui%lib{imgui}
impl_libs = # Implementation dependencies.

platform_libs = d3d12.lib d3dcompiler.lib dxgi.lib

lib{imgui-render-dx12}: {hxx cxx}{**} $impl_libs $intf_libs

# Build options.
out_pfx_inc = [dir_path] $out_root/imgui/
src_pfx_inc = [dir_path] $src_root/imgui/

cxx.libs =+ $platform_libs
cxx.poptions =+ "-I$out_pfx_inc" "-I$src_pfx_inc" -DIMGUI_EXPORT

{hbmia obja}{*}: cxx.poptions += -DIMGUI_PLATFORM_DX12_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DIMGUI_PLATFORM_DX12_SHARED_BUILD

# Export options.
lib{imgui-render-dx12}:
{
    cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
    cxx.export.libs = $intf_libs $platform_libs
}

liba{imgui-render-dx12}: cxx.export.poptions += -DIMGUI_PLATFORM_DX12_STATIC
libs{imgui-render-dx12}: cxx.export.poptions += -DIMGUI_PLATFORM_DX12_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
    lib{imgui-render-dx12}: bin.lib.version = "-$version.project_id"
else
    lib{imgui-render-dx12}: bin.lib.version = "-$version.major.$version.minor"

hxx{*}:
{
    install = include/imgui/
    install.subdirs = true
}