intf_libs = # Interface dependencies.
import intf_libs += libimgui%lib{imgui}

platform_libs = # Platform specific libraries.
if ($cxx.target.system == 'mingw32')
	platform_libs += -ld3d9
else
	platform_libs += d3d9.lib

lib{imgui-render-dx9}: {hxx cxx}{**} $intf_libs

cxx.libs += $platform_libs
cxx.poptions += "-I$out_base" "-I$src_base" -DIMGUI_IMPL_EXPORT

# Export options.
lib{imgui-render-dx9}:
{
    cxx.export.poptions = "-I$out_base" "-I$src_base"
    cxx.export.libs = $intf_libs $platform_libs
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
    lib{imgui-render-dx9}: bin.lib.version = "-$version.project_id"
else
    lib{imgui-render-dx9}: bin.lib.version = "-$version.major.$version.minor"

hxx{*}:
{
    install = include/imgui/backends/
}
