impl_libs = # Implementation libs.
import impl_libs += libimgui-platform-win32-docking%lib{imgui-platform-win32-docking}
import impl_libs += libimgui-render-dx9-docking%lib{imgui-render-dx9-docking}

exe{example_win32_dx9} : cxx{*} $impl_libs
