impl_libs = # Implementation libs.
import impl_libs += libimgui-platform-win32-docking%lib{imgui-platform-win32-docking}
import impl_libs += libimgui-render-dx12-docking%lib{imgui-render-dx12-docking}

exe{example_win32_dx12} : cxx{*} $impl_libs
