impl_libs = # Implementation libs.
import impl_libs += libimgui-platform-win32%lib{imgui-platform-win32}
import impl_libs += libimgui-render-dx9%lib{imgui-render-dx9}

exe{example_win32_dx9} : cxx{*} $impl_libs
