impl_libs = # Implementation libs.
import impl_libs += libimgui-platform-glfw%lib{imgui-platform-glfw}
import impl_libs += libimgui-render-opengl2%lib{imgui-render-opengl2}

exe{example_glfw_opengl2} : cxx{*} $impl_libs
