intf_libs = # Interface dependencies.
import intf_libs += libimgui%lib{imgui}

platform_libs = # Platform specific libraries.
if ($cxx.target.system == 'mingw32')
	platform_libs += -ld3d10 -ld3dcompiler
else
	platform_libs += d3d10.lib d3dcompiler.lib

lib{imgui-render-dx10}: {hxx cxx}{**} $intf_libs
lib{imgui-render-dx10}: cxx.pkgconfig.include = include/ include/imgui/backends/

cxx.libs += $platform_libs
cxx.poptions += "-I$out_base/backends" "-I$src_base/backends" -DIMGUI_IMPL_EXPORT

# Export options.
lib{imgui-render-dx10}:
{
    cxx.export.poptions = "-I$out_base/backends" "-I$src_base/backends" "-I$out_root" "-I$src_root"
    cxx.export.libs = $intf_libs $platform_libs
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
    lib{imgui-render-dx10}: bin.lib.version = "-$version.project_id"
else
    lib{imgui-render-dx10}: bin.lib.version = "-$version.major.$version.minor"

hxx{*}:
{
    install = include/imgui/
    install.subdirs = true
}
