impl_libs = # Implementation libs.
import impl_libs += libimgui-platform-glfw-docking%lib{imgui-platform-glfw-docking}
import impl_libs += libimgui-render-metal-docking%lib{imgui-render-metal-docking}
