intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

lib{imgui-core}: {cxx hxx}{*}

# Build options.
out_pfx_inc = [dir_path] $out_root/imgui/
src_pfx_inc = [dir_path] $src_root/imgui/

cxx.poptions =+ "-I$out_pfx_inc" "-I$src_pfx_inc"

{hbmia obja}{*}: cxx.poptions += -DIMGUI_CORE_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DIMGUI_CORE_SHARED_BUILD

# Export options.
lib{imgui-core}:
{
    cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
    cxx.export.libs = $intf_libs
}

liba{imgui-core}: cxx.export.poptions += -DIMGUI_CORE_STATIC
libs{imgui-core}: cxx.export.poptions += -DIMGUI_CORE_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
    lib{imgui-core}: bin.lib.version = "-$version.project_id"
else
    lib{imgui-core}: bin.lib.version = "-$version.major.$version.minor"

hxx{*}:
{
    install = include/imgui-core/
    install.subdirs = true
}